### ISSUE TITLE
DrHeader exit with exit code 0 when detecting issues

### ISSUE THREAD

**Issue by juan-medina** [Santandersecurityresearch/DrHeader#101]
* drHEADer version: 1.1.1
* Python version: 3.6.9
* Operating System: Linux Mint

DrHeader exit with exit code 0 when detecting issues, it should return a non zero code, then if execute via command-line tools we could use the exit code to understand if there were any errors.

```bash
$ drheader scan single https://santander.com
....

$ echo $?                              
0
```

When providing invalid arguments, or invalid URLs is already returning a non zero exit code.

```bash
$ drheader scan single https://owasp.com
Error: Failed to get headers.

$ echo $?                              
1
```

**Comment by juan-medina** [comment]
I've done a PR for this

**Comment by pealtrufo** [comment]
Thanks @juan-medina 
Closing this issue as it is duplicated with #74
