### ISSUE TITLE
DrHeader importer is submitted in defectdojo  

### ISSUE THREAD

**Issue by SPoint42** [Santandersecurityresearch/DrHeader#130]
See : 
https://github.com/DefectDojo/django-DefectDojo/pull/2846/files

**Comment by javixeneize** [comment]
Wow. This is amazing! Do you need anything from our side to help with this integration? We are more than happy to help with anything you might need

**Comment by SPoint42** [comment]
nothing, I just need to finish the unittestings for defect. 
This is a first WIP.

**Comment by SPoint42** [comment]
sucessfully merge to defectdojo-dev today
