### ISSUE TITLE
Please release 1.7.0 to include features. 

### ISSUE THREAD

**Issue by manuel-sommer** [Santandersecurityresearch/DrHeader#231]
As the last release (1.6.0) is already multiple month old, could you release a new version (1.7.0)?

I am waiting for the possibility to include custom severity settings via rules.yml

**Comment by emilejq** [comment]
Hi @manuel-sommer,

We'll be releasing a new version in the next few days

**Comment by emilejq** [comment]
Hi @manuel-sommer,

Version 1.7.0 has been released

**Comment by manuel-sommer** [comment]
Thank you @emilejq
