### ISSUE TITLE
Advance DrHEADer finding output to be more verbose.

### ISSUE THREAD

**Issue by manuel-sommer** [Santandersecurityresearch/DrHeader#252]
* drHEADer version: 1.7.0

Looking at the findings itself, it is not possible to figure out which values are expected for the scanned target. Please improve the output of the scanner especially for expected and avoid values.

**Comment by emilejq** [comment]
Can you post an example? Expected values are output in the `expected` key.

Example:

```json
{
    "rule": "Cache-Control",
    "message": "Value does not match security policy",
    "severity": "high",
    "value": "private, max-age=0",
    "expected": [
        "no-store",
        "max-age=0"
    ],
    "delimiter": ","
}
```

Thanks
