### ISSUE TITLE
Remove case validators in headers

### ISSUE THREAD

**Issue by javixeneize** [Santandersecurityresearch/DrHeader#60]
According to RFC 2616 https://www.w3.org/Protocols/rfc2616/rfc2616.html and their updates (7230-7237), headers are not case sensitive. 

The tool is doing an exact match between rules and values received, so it should do a case insensitive validation

**Comment by amias-channer** [comment]
this is a good idea , heres a direct link to the relevant section 
https://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.2

**Comment by amias-channer** [comment]
which has been replaced by 

> Each header field consists of a case-insensitive field name followed
   by a colon (":"), optional leading whitespace, the field value, and
   optional trailing whitespace.

https://tools.ietf.org/html/rfc7230#section-3.2
