### ISSUE TITLE
configurable toggle to fail pipelines when issues are found

### ISSUE THREAD

**Issue by actuallyjamez** [Santandersecurityresearch/DrHeader#74]
drHEADers CLI exit status is currently always zero, regardless of any issues found during a scan.

Adding an option to fail with the correct error statuses would allow pipelines to gracefully fail builds if unwanted headers were identified.

**Comment by javixeneize** [comment]
Hi @actuallyjamez 
We are currently planning 1.2.0 release in April and were thinking of including this issue. Would you be happy to take this issue or is it fine to move it to next release?
Thanks

**Comment by juan-medina** [comment]
Ops I miss this issue, I did already a PR and and issue for this that could be deleted

https://github.com/Santandersecurityresearch/DrHeader/pull/102
https://github.com/Santandersecurityresearch/DrHeader/issues/101

**Comment by pealtrufo** [comment]
Thanks guys. Change in #102 has already been released in DrHeader v1.2.0
