### ISSUE TITLE
Produce Junit report from DrHeader output

### ISSUE THREAD

**Issue by jhbarrantes** [Santandersecurityresearch/DrHeader#77]
## Description

It will be great if DrHeader can produce kind of report in JUnit format, that we can then parse in Jenkins to be use as a traceable source for historic issues. 
In addition, this report could be used to break pipelines when issues are present, as per JUnit Jenkins plugin functionality.

**Comment by amias-channer** [comment]
It should be doing this already in the GitHub action script for pull
requests.

Be careful about adding it the main project because it will rewire stdout
and stdin.

**Comment by jhbarrantes** [comment]
> It should be doing this already in the GitHub action script for pull requests. Be careful about adding it the main project because it will rewire stdout and stdin.
> […](#)

I'm not considering producing any kind of modification on the report console output. What I'm trying to produce is a new file output, with using a junit readable file. So basically translating your report into something that Junit can understand as "failed" cases, in case the simple scan return errors. We can discuss this tomorrow is that's not clear enough.

**Comment by pealtrufo** [comment]
Thanks @jhbarrantes 
Closing!
