### ISSUE TITLE
Release is missing a Tag

### ISSUE THREAD

**Issue by amias-channer** [Santandersecurityresearch/DrHeader#85]
* drHEADer version: Merge pull request #84 from Santandersecurityresearch/release_test
* Python version: n/a
* Operating System: n/a

### Description

The release doesn't have a tag so its not getting a version number. 

if you have switched the github actions plugin used it might not be doing all the stages the previous one did.  

i noticed this issue because i saw this in the release section 
![drheader_no_tag](https://user-images.githubusercontent.com/505684/79987752-b6d36900-84a5-11ea-8ab5-d02b6b74bbfb.png)

the tag icon doesn't have a value .

this plugin can make tags for you 
https://github.com/marketplace/actions/github-create-tag-release

**Comment by javixeneize** [comment]
Yes, i am on it :)

**Comment by javixeneize** [comment]
Ok, this is kind of fixed now. I have a couple of things i would like to improve:

1 - As it is now, it only runs the release flow when there is a new tag created. Ideally, i would like to trigger this every time a new push is done in master, and i want it to generate a tag automatically too.

2 - I'm not 100% sure about that, but i think the upload asset action doesn't accept wildcards. We have  the asset_path set to ./dist/*.whl

Apart from that, i have added a step to push to pypi, which is what i was initially looking for, but it got.... a bit more complicated that that
